# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(878, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = CustomWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 110, 891, 281))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 550, 101, 25))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(580, 150, 54, 17))
        self.label_3.setText("")
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(190, 10, 451, 61))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 181, 101))
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(190, 60, 311, 21))
        self.label_4.setObjectName("label_4")
        self.pushButton_fwd = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fwd.setGeometry(QtCore.QRect(350, 470, 101, 25))
        self.pushButton_fwd.setObjectName("pushButton_fwd")
        self.pushButton_bwd = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_bwd.setGeometry(QtCore.QRect(350, 510, 101, 25))
        self.pushButton_bwd.setObjectName("pushButton_bwd")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(290, 390, 20, 211))
        self.line.setMinimumSize(QtCore.QSize(3, 0))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(110, 390, 91, 61))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(560, 390, 131, 61))
        self.label_8.setObjectName("label_8")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setEnabled(True)
        self.radioButton.setGeometry(QtCore.QRect(710, 570, 171, 23))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(330, 430, 141, 161))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 141, 41))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(610, 450, 221, 111))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.window_lower = window_lower(self.frame_2)
        self.window_lower.setGeometry(QtCore.QRect(140, 70, 61, 25))
        self.window_lower.setObjectName("window_lower")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(20, 70, 91, 20))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.window = window(self.frame_2)
        self.window.setGeometry(QtCore.QRect(140, 40, 61, 25))
        self.window.setClearButtonEnabled(False)
        self.window.setObjectName("window")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 91, 20))
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 221, 31))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.frame_2.raise_()
        self.frame.raise_()
        self.graphicsView.raise_()
        self.pushButton.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_4.raise_()
        self.pushButton_fwd.raise_()
        self.pushButton_bwd.raise_()
        self.line.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.radioButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "OFF"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:26pt; font-weight:600; color:#cc0000;\">Motor Control Interface</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/Logos/logos_small.png\"/></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Challenge for post HL_2018_Q4_028</span></p></body></html>"))
        self.pushButton_fwd.setText(_translate("MainWindow", "FORWARD"))
        self.pushButton_bwd.setText(_translate("MainWindow", "BACKWARD"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#000000;\">Status</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#000000;\">Controls</span></p></body></html>"))
        self.radioButton.setText(_translate("MainWindow", "Circuit Breaker Closed"))
        self.label_9.setText(_translate("MainWindow", "MOTOR CONTROLS"))
        self.label.setText(_translate("MainWindow", "Hysteresis Value"))
        self.label_2.setText(_translate("MainWindow", "Max. Threshold"))
        self.label_10.setText(_translate("MainWindow", "TEMPERATURE LIMITS"))

from plotter import CustomWidget
from temp_input_gui import window
from temp_input_gui_lower import window_lower
import image_resource_rc
